# EDA (Exploratory Data Analysis)

In [8]:
import warnings

import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
warnings.filterwarnings("ignore")
import os
import sys

In [4]:
#loading the data
df = pd.read_csv('../Data/data.csv')

Data Inspection

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1666 entries, 0 to 1665
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1666 non-null   int64
 1   slug              1666 non-null   object
 2   title             1666 non-null   object
 3   imgs              1666 non-null   object
 4   brand             773 non-null    object
 5   category          1666 non-null   object
 6   vendor            1666 non-null   object
 7   used              1666 non-null   int64
 8   address           544 non-null    object
 9   availability      1079 non-null   object
 10  currency          1666 non-null   object
 11  original_price    1649 non-null   float64
 12  discounted_price  739 non-null    float64
 13  specifications    1666 non-null   object
 14  description       299 non-null    object
 15  delivery_fee      107 non-null    float64
 16  delivery_details  0 non-null      float64
 17  warranty          500 non-null    object
 18  warranty_type     389 non-null    object
 19  average_rating    900 non-null    float64
 20  num_ratings       900 non-null    float64
 21  reviews           1666 non-null   object
dtypes: float64(6), int64(2), object(14)
memory usage: 286.5+ KB

In [6]:
df.describe

<bound method NDFrame.describe of         id                                               slug  \
0        0  https://www.mega.pk/mobiles_products/23522/Not...
1        1  https://www.mega.pk/mobiles_products/23458/Opp...
2        2  https://www.mega.pk/mobiles_products/24393/Tec...
3        3  https://www.mega.pk/mobiles_products/24259/Viv...
4        4  https://www.mega.pk/mobiles_products/24204/App...
...    ...                                                ...
1661  1661  https://priceoye.pk/laptops/apple/apple-macboo...
1662  1662  https://priceoye.pk/laptops/apple/apple-macboo...
1663  1663  https://priceoye.pk/laptops/hp/hp-chromebook-1...
1664  1664  https://priceoye.pk/laptops/dell/dell-inspiron...
1665  1665  https://priceoye.pk/laptops/dell/dell-inspiron...

                                                  title  \
0     Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...
1     Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...
2                                       Tecno Spark 10
3                                          Vivo V27 5G
4                              Apple Iphone 15 Pro Max
...                                                 ...
1661      Apple MacBook Air 13.3 Inches M1 Chip (MGN63)
1662                          Apple MacBook Pro (MKGP3)
1663                                HP Chromebook 14 G5
1664  Dell Inspiron 3515 15.6 inches AMD Ryzen 5 345...
1665  Dell Inspiron 5510 15.6 Inches 11th Gen Core i...

                                                   imgs  brand category  \
0     ['https://www.mega.pk/items_images/Nothing+Pho...    NaN   Mobile
1     ['https://www.mega.pk/items_images/Oppo+F21+Pr...   OPPO   Mobile
2     ['https://www.mega.pk/items_images/Tecno+Spark...  Tecno   Mobile
3     ['https://www.mega.pk/items_images/Vivo+V27+5G...   Vivo   Mobile
4     ['https://www.mega.pk/items_images/Apple+Iphon...  Apple   Mobile
...                                                 ...    ...      ...
1661  ['https://images.priceoye.pk/apple-macbook-air...    NaN   Laptop
1662  ['https://images.priceoye.pk/apple-macbook-pro...    NaN   Laptop
1663  ['https://images.priceoye.pk/hp-chromebook-14-...    NaN   Laptop
1664  ['https://images.priceoye.pk/dell-inspiron-351...    NaN   Laptop
1665  ['https://images.priceoye.pk/dell-inspiron-551...    NaN   Laptop

        vendor  used                                            address  \
0      MEGA.PK     0  Office 11, 12, 14 Basement Ahmed Center, I-8 M...
1      MEGA.PK     0  Office 11, 12, 14 Basement Ahmed Center, I-8 M...
2      MEGA.PK     0  Office 11, 12, 14 Basement Ahmed Center, I-8 M...
3      MEGA.PK     0  Office 11, 12, 14 Basement Ahmed Center, I-8 M...
4      MEGA.PK     0  Office 11, 12, 14 Basement Ahmed Center, I-8 M...
...        ...   ...                                                ...
1661  PriceOye     0                                                NaN
1662  PriceOye     0                                                NaN
1663  PriceOye     0                                                NaN
1664  PriceOye     0                                                NaN
1665  PriceOye     0                                                NaN

       availability  ... discounted_price  \
0               NaN  ...              NaN
1               NaN  ...              NaN
2       Coming Soon  ...              NaN
3       Coming Soon  ...              NaN
4       Coming Soon  ...              NaN
...             ...  ...              ...
1661  Not Available  ...         269999.0
1662  Not Available  ...         362999.0
1663  Not Available  ...              NaN
1664  Not Available  ...         134499.0
1665  Not Available  ...              NaN

                                         specifications  description  \
0     {'RAM': '8GB', 'Memory quantity': '', 'Interna...          NaN
1     {'RAM': '8gb', 'Memory quantity': '', 'Interna...          NaN
2     {'RAM': '4GB,8GB', 'Memory quantity': '', 'Int...          NaN
3     {'RAM': '8GB,12GB', 'Memory quantity': '', 'In...          NaN
4     {'RAM': '8GB', 'Memory quantity': '', 'Interna...          NaN
...                                                 ...          ...
1661  {'Dimensions': 'N/A', 'Weight': '2.8 pounds (1...          NaN
1662  {'Dimensions': '0.61 x 12.31 x 8.71 inches', '...          NaN
1663  {'Dimensions': '337 x 226 x 18.3 mm', 'Weight'...          NaN
1664  {'Dimensions': '17.50x358.50x 235.56 mm', 'Wei...          NaN
1665  {'Dimensions': '14.6x 356.06x 228.9 mm', 'Weig...          NaN

     delivery_fee delivery_details  warranty  warranty_type average_rating  \
0             NaN              NaN       NaN            NaN            NaN
1             NaN              NaN       NaN            NaN            NaN
2             NaN              NaN    1 year            NaN            NaN
3             NaN              NaN    1 year            NaN            NaN
4             NaN              NaN       NaN            NaN            NaN
...           ...              ...       ...            ...            ...
1661          NaN              NaN       NaN            NaN            5.0
1662          NaN              NaN       NaN            NaN            5.0
1663          NaN              NaN       NaN            NaN            5.0
1664          NaN              NaN       NaN            NaN            5.0
1665          NaN              NaN       NaN            NaN            5.0

     num_ratings  reviews
0            NaN       []
1            NaN       []
2            NaN       []
3            NaN       []
4            NaN       []
...          ...      ...
1661         1.0       []
1662         1.0       []
1663         1.0       []
1664         1.0       []
1665         1.0       []

[1666 rows x 22 columns]>

In [7]:
df.head()

,id,slug,title,imgs,brand,category,vendor,used,address,availability,...,discounted_price,specifications,description,delivery_fee,delivery_details,warranty,warranty_type,average_rating,num_ratings,reviews
0,0,https://www.mega.pk/mobiles_products/23522/Not...,Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...,['https://www.mega.pk/items_images/Nothing+Pho...,NaN,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",NaN,...,NaN,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
1,1,https://www.mega.pk/mobiles_products/23458/Opp...,Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...,['https://www.mega.pk/items_images/Oppo+F21+Pr...,OPPO,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",NaN,...,NaN,"{'RAM': '8gb', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,https://www.mega.pk/mobiles_products/24393/Tec...,Tecno Spark 10,['https://www.mega.pk/items_images/Tecno+Spark...,Tecno,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '4GB,8GB', 'Memory quantity': '', 'Int...",NaN,NaN,NaN,1 year,NaN,NaN,NaN,[]
3,3,https://www.mega.pk/mobiles_products/24259/Viv...,Vivo V27 5G,['https://www.mega.pk/items_images/Vivo+V27+5G...,Vivo,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '8GB,12GB', 'Memory quantity': '', 'In...",NaN,NaN,NaN,1 year,NaN,NaN,NaN,[]
4,4,https://www.mega.pk/mobiles_products/24204/App...,Apple Iphone 15 Pro Max,['https://www.mega.pk/items_images/Apple+Iphon...,Apple,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]

In [9]:
df.shape

(1666, 22)

In [10]:
df.tail()

,id,slug,title,imgs,brand,category,vendor,used,address,availability,...,discounted_price,specifications,description,delivery_fee,delivery_details,warranty,warranty_type,average_rating,num_ratings,reviews
1661,1661,https://priceoye.pk/laptops/apple/apple-macboo...,Apple MacBook Air 13.3 Inches M1 Chip (MGN63),['https://images.priceoye.pk/apple-macbook-air...,NaN,Laptop,PriceOye,0,NaN,Not Available,...,269999.0,"{'Dimensions': 'N/A', 'Weight': '2.8 pounds (1...",NaN,NaN,NaN,NaN,NaN,5.0,1.0,[]
1662,1662,https://priceoye.pk/laptops/apple/apple-macboo...,Apple MacBook Pro (MKGP3),['https://images.priceoye.pk/apple-macbook-pro...,NaN,Laptop,PriceOye,0,NaN,Not Available,...,362999.0,"{'Dimensions': '0.61 x 12.31 x 8.71 inches', '...",NaN,NaN,NaN,NaN,NaN,5.0,1.0,[]
1663,1663,https://priceoye.pk/laptops/hp/hp-chromebook-1...,HP Chromebook 14 G5,['https://images.priceoye.pk/hp-chromebook-14-...,NaN,Laptop,PriceOye,0,NaN,Not Available,...,NaN,"{'Dimensions': '337 x 226 x 18.3 mm', 'Weight'...",NaN,NaN,NaN,NaN,NaN,5.0,1.0,[]
1664,1664,https://priceoye.pk/laptops/dell/dell-inspiron...,Dell Inspiron 3515 15.6 inches AMD Ryzen 5 345...,['https://images.priceoye.pk/dell-inspiron-351...,NaN,Laptop,PriceOye,0,NaN,Not Available,...,134499.0,"{'Dimensions': '17.50x358.50x 235.56 mm', 'Wei...",NaN,NaN,NaN,NaN,NaN,5.0,1.0,[]
1665,1665,https://priceoye.pk/laptops/dell/dell-inspiron...,Dell Inspiron 5510 15.6 Inches 11th Gen Core i...,['https://images.priceoye.pk/dell-inspiron-551...,NaN,Laptop,PriceOye,0,NaN,Not Available,...,NaN,"{'Dimensions': '14.6x 356.06x 228.9 mm', 'Weig...",NaN,NaN,NaN,NaN,NaN,5.0,1.0,[]

In [11]:

#summary statistics of the dataset
df.describe(include = 'all')

,id,slug,title,imgs,brand,category,vendor,used,address,availability,...,discounted_price,specifications,description,delivery_fee,delivery_details,warranty,warranty_type,average_rating,num_ratings,reviews
count,1666.00000,1666,1666,1666,773,1666,1666,1666.00000,544,1079,...,739.000000,1666,299,107.0,0.0,500,389,900.000000,900.000000,1666
unique,NaN,1666,1657,1659,22,4,5,NaN,2,4,...,NaN,1595,299,NaN,NaN,5,2,NaN,NaN,488
top,NaN,https://priceoye.pk/laptops/dell/dell-inspiron...,Microsoft Surface Pro 9 Tablet Laptop,['https://www.czone.com.pk/images/thumbnails-l...,Apple,Laptop,PriceOye,NaN,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Avaiable,...,NaN,"{'Processor Type': 'Apple M1 8-Core CPU', 'Ins...","Apple Macbook Pro 16"" MNWA3LL/A Apple M2 Max C...",NaN,NaN,1 year,International Warranty,NaN,NaN,[]
freq,NaN,1,3,2,221,575,892,NaN,368,513,...,NaN,6,1,NaN,NaN,469,338,NaN,NaN,1178
mean,832.50000,NaN,NaN,NaN,NaN,NaN,NaN,0.02521,NaN,NaN,...,41247.326116,NaN,NaN,0.0,NaN,NaN,NaN,4.992222,13.331111,NaN
std,481.07709,NaN,NaN,NaN,NaN,NaN,NaN,0.15681,NaN,NaN,...,96631.352491,NaN,NaN,0.0,NaN,NaN,NaN,0.096925,43.200123,NaN
min,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,...,1149.000000,NaN,NaN,0.0,NaN,NaN,NaN,3.500000,1.000000,NaN
25%,416.25000,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,...,3899.500000,NaN,NaN,0.0,NaN,NaN,NaN,5.000000,1.000000,NaN
50%,832.50000,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,...,6599.000000,NaN,NaN,0.0,NaN,NaN,NaN,5.000000,1.000000,NaN
75%,1248.75000,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,...,29299.000000,NaN,NaN,0.0,NaN,NaN,NaN,5.000000,6.000000,NaN
max,1665.00000,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,NaN,NaN,...,794999.000000,NaN,NaN,0.0,NaN,NaN,NaN,5.000000,751.000000,NaN

In [12]:
#missing values 
df.isnull().sum()

id                     0
slug                   0
title                  0
imgs                   0
brand                893
category               0
vendor                 0
used                   0
address             1122
availability         587
currency               0
original_price        17
discounted_price     927
specifications         0
description         1367
delivery_fee        1559
delivery_details    1666
warranty            1166
warranty_type       1277
average_rating       766
num_ratings          766
reviews                0
dtype: int64

In [13]:
#identifying garberge values 
for i in df.select_dtypes(include="object").columns:
           print(df[i].value_counts())
           print("***"*10)

slug
https://priceoye.pk/laptops/dell/dell-inspiron-5510-15-6-inches-11th-gen-core-i5-11300h-8gb-256gb         1
https://www.mega.pk/mobiles_products/23522/Nothing-Phone-1-8GB-RAM-256GB-Storage-Non-PTA-5G-Black.html    1
https://priceoye.pk/laptops/hp/hp-eg0503tx-15-6-inches-core-i5-11thgen-8gb-ram-512gbssd                   1
https://priceoye.pk/laptops/hp/hp-fq5099tu-15-6-inches-core-i5-12gen-8gb-ram-512gbssd                     1
https://priceoye.pk/laptops/lenovo/lenovo-ideapad-3-15-6-inches-11th-gen-core-i5-8gb-1tb-hdd              1
                                                                                                         ..
https://www.mega.pk/mobiles_products/24418/Tecno-Sparx-S9-2GB-RAM-32GB-Storage-PTA-Approved.html          1
https://www.mega.pk/mobiles_products/24114/Realme-GT3.html                                                1
https://www.mega.pk/mobiles_products/24204/Apple-Iphone--15-Pro-Max.html                                  1
https://www.mega.pk/mobiles_products/24259/Vivo-V27-5G.html                                               1
https://www.mega.pk/mobiles_products/24393/Tecno-Spark-10.html                                            1
Name: count, Length: 1666, dtype: int64
******************************
title
Microsoft Surface Pro 9 Tablet Laptop                                      3
Microsoft Surface Laptop 5 12th Gen Core i7-1255U                          2
Apple iPhone 14 Pro Max                                                    2
Microsoft Surface Pro 8                                                    2
Samsung Galaxy Tab A7 Lite                                                 2
                                                                          ..
HP EG0503TX 15.6 Inches Core i5 11thGen (8GB RAM - 512GBSSD)               1
HP EQ2179AU 15.6 Inches AMD Ryzen 3 Core i5 11thGen (4GB RAM -256GBSSD)    1
Lenovo Laptop Ideapad 3 15.6 Inches 11th Gen Core i5 (8GB - 1TB HDD)       1
HP FQ5099TU 15.6 Inches Core i7 12Gen (8GB RAM - 512GBSSD)                 1
VGO TEL i20                                                                1
Name: count, Length: 1657, dtype: int64
******************************
imgs
['https://www.czone.com.pk/images/thumbnails-large/copy-7-czone.com.pk-1540-13145-230422125548.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-6-czone.com.pk-1540-13145-230422125548.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-8-czone.com.pk-1540-13145-230422125549.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-9-czone.com.pk-1540-13145-230422125549.jpg']                                            2
['https://static3.webx.pk/files/4012/Images/Thumbnails-Large/copy-6-4012-721340-101221110721435.jpg', 'https://static3.webx.pk/files/4012/Images/Thumbnails-Large/copy-2-4012-721340-101221110810154.jpg', 'https://static3.webx.pk/files/4012/Images/Thumbnails-Large/copy-7-4012-721340-101221110818563.jpg', 'https://static3.webx.pk/files/4012/Images/Thumbnails-Large/copy-3-4012-721340-101221110818704.jpg']                                        2
['https://www.czone.com.pk/images/thumbnails-large/copy-5-czone.com.pk-1540-14433-280223071406.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-6-czone.com.pk-1540-14433-280223071407.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-7-czone.com.pk-1540-14433-280223071407.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-8-czone.com.pk-1540-14433-280223071408.jpg']                                            2
['https://www.czone.com.pk/images/thumbnails-large/copy-copy-copy-1-czone.com.pk-1540-13574-230822023619.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-copy-copy-3-czone.com.pk-1540-13574-230822023620.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-copy-copy-2-czone.com.pk-1540-13574-230822023620.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-copy-copy-4-czone.com.pk-1540-13574-230822023620.jpg']    2
['https://www.czone.com.pk/images/thumbnails-large/copy-1-czone.com.pk-1-1540-14432-280223070320.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-2-czone.com.pk-1-1540-14432-280223070320.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-3-czone.com.pk-1-1540-14432-280223070320.jpg', 'https://www.czone.com.pk/images/thumbnails-large/copy-4-czone.com.pk-1-1540-14432-280223070321.jpg']                                    2
                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
['https://images.priceoye.pk/hp-eg0503tx-15-6-inches-core-i5-12gen-8gb-ram-512gbssd-pakistan-priceoye-72a21-270x270.webp']                                                                                                                                                                                                                                                                                                                                  1
['https://images.priceoye.pk/hp-eq2179au-15-6-inches-core-i5-11thgen-4gb-ram-256gbssd-pakistan-priceoye-k3t2s-270x270.webp']                                                                                                                                                                                                                                                                                                                                1
['https://images.priceoye.pk/lenovo-ideapad-3-15-6-inches-11th-gen-core-i5-8gb-1tb-hdd-pakistan-priceoye-g743d-270x270.webp']                                                                                                                                                                                                                                                                                                                               1
['https://images.priceoye.pk/hp-fq5099tu-15-6-inches-core-i5-12gen-8gb-ram-512gbssd-pakistan-priceoye-65vcq-270x270.webp']                                                                                                                                                                                                                                                                                                                                  1
['https://images.priceoye.pk/lenovo-thinkbook-1165g7-14-inches-11th-gen-core-i7-8-gb-1tb-hdd-pakistan-priceoye-rhksy-270x270.webp']                                                                                                                                                                                                                                                                                                                         1
Name: count, Length: 1659, dtype: int64
******************************
brand
Apple        221
HP           140
Dell          66
Lenovo        48
Samsung       47
Hp            44
Microsoft     42
Acer          37
Asus          20
OnePlus       16
Realme        13
Infinix       12
Xiaomi        11
Tecno         11
OPPO          10
Vivo          10
MSI            9
Google         9
Sparx          2
Red Magic      2
Nokia          2
Motorola       1
Name: count, dtype: int64
******************************
category
Laptop     575
Mobile     522
Earbuds    363
Watch      206
Name: count, dtype: int64
******************************
vendor
PriceOye        892
MEGA.PK         368
ComputerZone    176
TechGlobe       123
Paklap          107
Name: count, dtype: int64
******************************
address
Office 11, 12, 14 Basement Ahmed Center, I-8 Markaz, Islamabad, Pakistan         368
FL 4/20, Main Rashid Minhas Road, Gulshan-e-Iqbal Block-5, Karachi, Pakistan.    176
Name: count, dtype: int64
******************************
availability
Avaiable              513
Not Available         447
Available on Order    102
Coming Soon            17
Name: count, dtype: int64
******************************
currency
PKR    1666
Name: count, dtype: int64
******************************
specifications
{'Processor Type': 'Apple M1 8-Core CPU', 'Installed RAM': '8-Core GPU', 'Hard drive size': '16-Core Neural Engine'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   6
{'Processor Type': 'Apple M2 8-Core Chip', 'Installed RAM': '8GB Unified RAM', 'Hard drive size': '512GB SSD', 'Graphics memory': '10-Core GPU'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       5
{'Processor Type': '12th Generation Intel Core i7-1255U', 'Installed RAM': '8GB DDR4', 'Hard drive size': '512GB NVMe M.2 SSD', 'Graphics memory': 'Intel Iris Xe'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5
{'Processor Type': 'Apple M2 chip 8-core CPU - 10-core GPU - 16-core Neural\xa0Engine', 'Installed RAM': '8GB RAM', 'Hard drive size': '256GB Storage'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                4
{'Processor Type': 'Apple M2 8-Core Chip', 'Installed RAM': '8GB Unified RAM', 'Hard drive size': '256GB SSD', 'Graphics memory': '8-Core GPU'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
{'Dimensions': '36.02 x 23.4 x 1.79 cm', 'Weight': '1.75 kg', 'Operating System': 'Windows 10 Home', 'Generation': '11th Generation', 'Screen Size': '15.6 Inches', 'Screen Resolution': 'Full HD (1920 x 1080)', 'Touch Screen': 'No', 'Backlit Keyboard': 'N/A', 'Internal Memory': '512 GB', 'RAM': '8 GB', 'Graphics Memory': 'N/A', 'Processor Type': 'Intel® Core™ i5-1135G7', 'Processor Speed': 'Intel® Core™ i5-1135G7 (up to 4.2 GHz with Intel® Turbo Boost Technology, 8 MB L3 cache, 4 cores)', 'Type': 'N/A', 'Bluetooth': 'Yes', 'Wireless/Wifi': 'Yes', 'USB': 'Yes', 'Camera': 'Yes', 'Fingerprint Reader': 'N/A'}    1
{'Dimensions': 'N/A', 'Weight': 'N/A', 'Operating System': 'Windows 11', 'Generation': 'N/A', 'Screen Size': '15.6 Inches', 'Screen Resolution': 'HD (1366×768), micro-edge, anti-glare, 250 nits, 45% NTSC', 'Touch Screen': 'No', 'Backlit Keyboard': 'N/A', 'Internal Memory': '256 GB SSD', 'RAM': '4GB', 'Graphics Memory': 'AMD Radeon Graphics', 'Processor Type': 'AMD Ryzen 3', 'Processor Speed': 'AMD Ryzen 3 5300U (Up to 3.8GHz)', 'Type': 'N/A', 'Bluetooth': 'Yes', 'Wireless/Wifi': 'null', 'USB': 'null', 'Camera': 'null', 'Fingerprint Reader': 'N/A'}                                                              1
{'Dimensions': 'N/A', 'Weight': '2.2kg (4.85lbs)', 'Operating System': 'N/A', 'Generation': '11th Generation', 'Screen Size': '15.6 Inches', 'Screen Resolution': '1920 x 1080', 'Touch Screen': 'No', 'Backlit Keyboard': 'N/A', 'Internal Memory': '1 TB HDD', 'RAM': '8 GB', 'Graphics Memory': 'Intel Iris® Xe Graphics', 'Processor Type': 'Intel Core i5-1135G7 (4C / 8T, 2.4 / 4.2GHz, 8MB)', 'Processor Speed': 'N/A', 'Type': '2 CELL', 'Bluetooth': 'Yes', 'Wireless/Wifi': 'Yes', 'USB': 'Yes', 'Camera': 'Yes', 'Fingerprint Reader': 'N/A'}                                                                               1
{'Dimensions': 'N/A', 'Weight': 'N/A', 'Operating System': 'Windows 11', 'Generation': '12th Generation', 'Screen Size': '15.6 Inches', 'Screen Resolution': 'Full HD (1920 x 1080), Micro-Edge, Anti-glare, 250 nits, 45%NTSC Display', 'Touch Screen': 'No', 'Backlit Keyboard': 'N/A', 'Internal Memory': '512 GB', 'RAM': '8 GB', 'Graphics Memory': 'Intel Iris Xe Graphics', 'Processor Type': 'Intel Core i7-1255U', 'Processor Speed': 'Intel Core i7-1255U 12th Generation', 'Type': 'N/A', 'Bluetooth': 'Yes', 'Wireless/Wifi': 'Yes', 'USB': 'Yes', 'Camera': 'Yes', 'Fingerprint Reader': 'N/A'}                           1
{'Dimensions': '17.9mm x 323mm x 218mm', 'Weight': '1.4 kg', 'Operating System': 'Windows 10 Pro', 'Generation': '11th Generation', 'Screen Size': '14 Inches', 'Screen Resolution': '1920 x 1080', 'Touch Screen': 'No', 'Backlit Keyboard': 'No', 'Internal Memory': '1 TB HDD', 'RAM': '8 GB', 'Graphics Memory': 'Intel Iris Xe Graphics', 'Processor Type': 'Intel Core i7 11th Generation', 'Processor Speed': 'Intel Core i7-1165G7 (up to 4.5 GHz, 12MB Cache)', 'Type': '3 cell 45 WHr battery', 'Bluetooth': 'Yes', 'Wireless/Wifi': 'Yes', 'USB': '3 Ports', 'Camera': '720p HD', 'Fingerprint Reader': 'Yes'}              1
Name: count, Length: 1595, dtype: int64
******************************
description
Apple Macbook Pro 16" MNWA3LL/A Apple M2 Max Chip, 32GB Ram, 1TB SSD, Backlit Keyboard, 16.2" Liquid Retina XDR, mac OS, Space Gray. The 16-inch MacBook Pro with M2 Pro and M2 Max takes power and speed to the next level, whether it’s on battery or plugged in. With a stunning Liquid Retina XDR display, all the ports you need, and all-day battery life—this pro laptop goes anywhere you need.                                         1
HP 15S-FQ5000NIA Laptop - Intel Core i3-1215U, 4GB, 256GB SSD, Intel Graphics, 15.6" HD Display, Jet black. Stay productive and entertained from anywhere with long-lasting battery life and a micro-edge display.                                                                                                                                                                                                                              1
HP 15s-FQ5004NIA Laptop - Intel Core i3-1215U - 4GB DDR4 - 256GB SSD - Intel Graphics - 15.6" HD Display - Natural Silver | 6G3G9EA. Stay productive and entertained from anywhere with long-lasting battery life and a micro-edge display.                                                                                                                                                                                                     1
Lenovo IdeaPad 3 15IAU7 Laptop - Intel Core i3-1215U, 4GB, 256GB SSD, 15.6" FHD Display | 82RK005YAK - Arctic Grey. The IdeaPad 3 is priced as an everyday-use laptop—but engineered as something much more. Premium Intel® processing—as well as powerful memory and storage options—means this PC delivers beyond expectations.                                                                                                               1
HP 15s-EQ2179AU Laptop - AMD Ryzen 3 5300U, 4GB, 256GB SSD, 15.6" HD Display, Windows 11 Home, Pale Gold (Official Warranty). Stay productive and entertained from anywhere with long battery life and micro-edge display.                                                                                                                                                                                                                      1
                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Acer Aspire 3 A315-59G-51WP Laptop - Intel Core i5-1235U, 8GB, 256GB SSD, NVIDIA GeForce MX550 2GB, Windows 11, 15.6" FHD Display, Pure Silver - NX.K6WSG.00E (Official Warranty). This entry-level laptop provides gives you all the performance you need whether at home, school or work. With plenty of Intel power and memory, all of your apps will run at a nice, smooth pace.                                                            1
HP 15s-EQ2180AU Laptop - AMD Ryzen 5 5500U, 8GB, 512GB SSD, 15.6" FHD Display, Windows 11, Pale Gold (Official Warranty). Stay productive and entertained from anywhere with long battery life and micro-edge display.                                                                                                                                                                                                                          1
Acer Aspire 5 A515-58P-55AK Laptop - Intel Core i5-1335U, 8GB, 512GB SSD, 15.6" FHD Display, Windows 11 | Local Warranty - NX.KHJSG.009. Whatever your task, do it all with the feature-packed Acer Aspire 5. Powered by the latest 13th Gen Intel® Core™ Processors for crisp multitasking to pursue your passions.                                                                                                                            1
HP 15S-FQ5886TU Laptop - Intel Core i5-1235U 12th Gen, 8GB, 512GB SSD, Intel Graphics, Windows 11, 15.6" FHD Display. Stay connected to what matters most with long-lasting battery life and a thin and portable, micro-edge bezel design. Built to keep you productive and entertained from anywhere, the HP 15.6-inch Laptop PC features reliable performance and an expansive display - letting you stream, surf and speed through tasks.    1

In [14]:
#checking duplicates
df.duplicated().sum()

np.int64(0)

In [15]:
# identifying date types
df.dtypes

id                    int64
slug                 object
title                object
imgs                 object
brand                object
category             object
vendor               object
used                  int64
address              object
availability         object
currency             object
original_price      float64
discounted_price    float64
specifications       object
description          object
delivery_fee        float64
delivery_details    float64
warranty             object
warranty_type        object
average_rating      float64
num_ratings         float64
reviews              object
dtype: object